spring:
  config:
    activate:
      on-Profile: "qa"#This allow us to tell spring boot when those profiles or file has to be activated
build:
  version: "2.0"
accounts:
  message: "Welcome to EazyBank accounts related QA APIs"
  contactDetails:
    name: "Smitha Ray-QA Lead"
    email: "smitha@gmail.com"
  onCallSupport:
    - (666) 265-3765
    - (666)734-8371
